apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
