FROM astronomerinc/ap-airflow:1.10.7-buster-onbuild

ENV AIRFLOW__SCHEDULER__STATSD_ON=True \
    AIRFLOW__SCHEDULER__STATSD_HOST=localhost \
    AIRFLOW__SCHEDULER__STATSD_PORT=8125 \
    AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow \
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
