install.packages('stringi')
install.packages('data.table')
install.packages('googleAuthR')
install.packages('googleCloudStorageR')
install.packages('stringr')
install.packages('mipfp')
install.packages('ISOweek')
install.packages('lubridate')