name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t "${PWD##*/}" .
      - run: docker run "${PWD##*/}" python -V | grep '3.6'
      - run: docker run "${PWD##*/}" version | grep '1.10.11'
