name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-airflow:2.2.3 .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-airflow:2.2.3
